language: ruby
sudo: false
env:
  global:
    - CC_TEST_REPORTER_ID=ca59e1eafbb34bd7ae0b3bac2710906a72ba7b1fa06c4c6dd9001427ccb20303
    - DB=mysql
branches:
  only:
    - master
language: ruby
rvm:
  - 2.3.1
before_script:
  - mysql -e 'create database LibraryManagementTool_test'
script:
  - bundle install
  - RAILS_ENV=test bundle exec rake db:reset
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare test
  - CODECLIMATE_REPO_TOKEN=ca59e1eafbb34bd7ae0b3bac2710906a72ba7b1fa06c4c6dd9001427ccb20303 bundle exec codeclimate-test-reporter