version: '2'
services:
  db:
    image: mysql:5.7.16
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
  libtool:
    build: .
    container_name: LibraryManagementTool
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/LibManagementTool
    ports:
      - "3000:3000"
    depends_on:
      - db
